### ISSUE TITLE
I still seem to be getting error with the following code

### ISSUE THREAD

**Issue by marcianx** [marcianx/downcast-rs#10]
I still seem to be getting error with the following code

```rust
let note: Ref<dyn EditableNote> = { ... };
match note.downcast_ref::<dyn Note>() {
  ...
}

```

```rust
error: the `downcast_ref` method cannot be invoked on a trait object
   --> webui/src/agents/notes_manager.rs:299:28
    |
299 |                 match note.downcast_ref::<dyn Note>() {
    |                            ^^^^^^^^^^^^
    | 
   ::: webui/src/editable.rs:20:1
    |
20  | impl_downcast!(EditableNote);
    | ----------------------------- this has a `Sized` requirement

```

Whereas it works fine when downcasting to a concrete struct
```rust
match note.downcast_ref::<MarkdownNote>() {
  ...
}
// works fine
```

I'm on the latest version of downcast-rs
downcast-rs = "1.2.0"

_Originally posted by @AgarwalPragy in https://github.com/marcianx/downcast-rs/issues/2#issuecomment-671087857_

**Comment by marcianx** [comment]
A few important points:
1. _(Sorry, this comment about `map` being necessary was completely incorrect. That's only if you want to keep an independent `Ref` around.)_ <strike>One can't pull a naked reference out of [`Ref`](https://doc.rust-lang.org/std/cell/struct.Ref.html#method.map) since `Ref`'s specific purpose is to keep track of the count of all outstanding borrows. So you need [`Ref::map`](https://doc.rust-lang.org/std/cell/struct.Ref.html#method.map) to get at the contents wrapped by the `Ref` (see example below) to produce a result that is also `Ref`-wrapped ([this issue has an involved example](https://github.com/marcianx/downcast-rs/issues/8)). However, given your claim that `note.downcast_ref::<MarkdownNote>()` works here seems to suggest that this is some other `Ref` that implements `Deref`? If so, then please ignore this point.</strike>
2. `downcast-rs` effectively adds convenience methods for downcasting from an arbitrary `dyn Trait` object (e.g. `dyn EditableNote`). The standard library [already supports downcasting from `dyn Any` trait objects](https://doc.rust-lang.org/std/any/index.html). The `Downcast` trait provided by this crate just adds convenience methods to go from `dyn Trait` to `dyn Any`, [and then delegates the downcasting to `dyn Any`](https://github.com/marcianx/downcast-rs/blob/74b75d93eda5206879bdb9d8c3bc40e18152f3fd/src/lib.rs#L282).
3. The consequence of 2 is that `downcast-rs` can't offer any functionality that `dyn Any` itself doesn't provide. Unfortunately per the `std::any` module doc:
      > Note that &dyn Any is limited to testing whether a value is of a specified concrete type, and cannot be used to test whether a type implements a trait.

     (Note that `Any`'s `type_id()` is type id of the concrete type.) There's thus no ability I know of that it has to downcast one trait object to another trait object.

Does this help explain why the code you provided doesn't work? If you are asking for something else, please feel free to clarify and reopen this issue.

**Comment by AgarwalPragy** [comment]
@marcianx Thanks for the clear explanation :) 

> here seems to suggest that this is some other Ref that implements Deref

I have the following
```rust
// Rc, RefCell are from std
note: Rc<RefCell<dyn EditableNote>> = { ... }
let note = note.borrow();        // Ref<dyn EditableNote>
match note.downcast_ref::<MarkdownNote>() {
   ...
}
```

**Comment by marcianx** [comment]
Ah, you know what, my first point was completely irrelevant since `Ref` does indeed implement `Deref` (not fully sure why I thought otherwise). Sorry about that! I definitely confused myself on that. Points 2 and 3 still stand, which is why your code unfortunately cannot work, sorry.
