### ISSUE TITLE
Support associated constants

### ISSUE THREAD

**Issue by vhdirk** [marcianx/downcast-rs#21]
I have a use case where I want to attach ID's to structures. I could do this with static getters, but having it directly accessible as a constant would be very cool:

example:
```rust
use downcast_rs::{impl_downcast, Downcast};

pub trait MyTrait: Downcast {
    const ID: u8;
    const SIZE: u32;
}
impl_downcast!(MyTrait assoc ID,SIZE);

```

**Comment by marcianx** [comment]
Could you clarify the requirements of your feature request? The base trait is not `dyn` compatible [if it has associated constants](https://doc.rust-lang.org/reference/items/traits.html#object-safety). So I'm not sure how downcasting would even apply.

So what functionality would you like from `downcast` here?

**Comment by vhdirk** [comment]
Ah, I didn't know that. Nevermind then :)
