### ISSUE TITLE
wrong number of type arguments in impl_downcast! with std::io::Result

### ISSUE THREAD

**Issue by Skasselbard** [marcianx/downcast-rs#3]
Hi,

I just walked into an error where I could not even compile your basic examples (between other code from me).

This code should reproduce the error:
```rust
#[macro_use]
extern crate downcast_rs;

use downcast_rs::Downcast;
use std::io::Result;

pub trait Base: Downcast {
}
impl_downcast!(Base);
```

The compiler aborted with this error:
```
error[E0244]: wrong number of type arguments: expected 1, found 2
  --> master/src/device/mod.rs:38:1
   |
   | impl_downcast!(Device);
   | ^^^^^^^^^^^^^^^^^^^^^^^ expected 1 type argument
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

Removing the import of `use std::io::Result` and using just `use std;` instead fixes the error.

If you can confirm this you might update the documentation with a hint to this? I can imagine that `Result` is often enough used to justify a mention.

**Comment by marcianx** [comment]
Sorry about that. Thanks for reporting! Will push 1.0.3 soon with the fix.
