### ISSUE TITLE
no_std support

### ISSUE THREAD

**Issue by dingelish** [marcianx/downcast-rs#4]
Hi there,

Do you mind make downcast-rs a `#![no_std]` crate by importing `Any` from `core::any::Any` and `Box` from `alloc::boxed::Alloc`? This change also requires an additional feature gate `#![feature(alloc)]` which is not yet stable. If this crate supports `no_std`, many embedded platforms would benefit a lot by directly use it from crates.io instead of maintaining their own `no_std` branch. I could provide PR if it's OK :) Thanks!

**Comment by marcianx** [comment]
I'll happy accept a PR. Thanks!

**Comment by dingelish** [comment]
PR created at 4d72113bf3f2e404f17be67427a74b639a6de811

Please check if version number needs update. Thanks!

**Comment by marcianx** [comment]
@dingelish: out of curiosity, does your `no_std` uses require the `Box` downcasting methods at all?

**Comment by dingelish** [comment]
Hey @marcianx , I'm maintaining on [rust-sgx-sdk](https://github.com/baidu/rust-sgx-sdk/) which provides an in-SGX-enclave Rust libstd (actually it's a specialized sgx_tstd for SGX) along with a set of ported crates.

At the beginning of this project I always do the following:

```
#![no_std]
#[macro_use]
extern crate sgx_tstd as std;
```

This is to override the default std with my sgx_tstd. So technically it is a `no_std` environment but with almost all `std` features including `Box`. Later I noticed that `xargo` could do the same thing. However, if I use `xargo` to maintain this project, it would not be able to publish to crates.io, because sgx_tstd cannot be published to crates.io under the name of `std`.

So  now, I've been maintaining the `cargo` branch and `xargo` "fake branch" at the same time, and the `cargo` branch is a `no_std` environment but with a customized `std` imported and needs `downcast-rs` with `Box` support.

I understand your concerns and I could fork your `downcast` and maintain a special branch for SGX as well :-)

**Comment by marcianx** [comment]
Ah ok. Thanks for the context. I had just been wondering whether it would have made sense to pursue `no_std` spring most of the operations but not the ones for `Box`.
