### ISSUE TITLE
Support Arc::downcast and Rc::downcast

### ISSUE THREAD

**Issue by Marwes** [marcianx/downcast-rs#7]
`Arc` and `Rc` supports downcasting as well. Do you plan/want to support this? I looked at implementing this but I think it requires a fair bit of duplication since `Arc` only works if the trait is `Send + Sync` but maybe there is a clean way of doing this.

https://doc.rust-lang.org/std/sync/struct.Arc.html#method.downcast
https://doc.rust-lang.org/std/rc/struct.Rc.html#method.downcast

**Comment by marcianx** [comment]
Sure can do, thanks for asking!
It's just that it's in a relatively recent release and thus not strictly backward-compatible. So I'll have to put it behind a feature.

Another alternative that I'd been considering was to bite the bullet, make a 2.0, and support the recently-stabilized Alloc trait also to support `nostd` use-cases as well. I'd need to read things up a bit. I've got a busy couple days, but I can get to this after.

**Comment by Marwes** [comment]
For the moment I just implemented it manually https://github.com/gluon-lang/gluon/blob/d606094a4aa84ee7d758492fda8d3b4403921bd2/vm/src/macros.rs#L30-L63

**Comment by marcianx** [comment]
Interestingly, I can't figure out a way to define an `Arc` unless the trait type was defined specifically with `trait Trait: 'static + Send + Sync` at least, which happens to be the case in yours, for example. I'm trying to figure out the cleanest way to conditionally add the `Arc` downcast implementation.

**Comment by marcianx** [comment]
Thanks again for the feature request! I just published 1.1.0 with this support and `Rc` should work out of the box.

To support `Arc` downcasting:
1. The trait needs to extend `DowncastSync` which extends `Downcast + Sync + Send`.
2. `impl_downcast!` needs a starting `sync`: e.g. `impl_downcast!(sync Trait)`.
